// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A SchoolInfoExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class SchoolInfoExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a SchoolInfoExtensions
	/// </summary>
	public SchoolInfoExtensions() : base ( StudentDTD.SCHOOLINFOEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected SchoolInfoExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;ScheduleDayType&gt;</c> element.
	/// </summary>
	/// <value> The <c>ScheduleDayType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ScheduleDayType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_SCHEDULEDAYTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_SCHEDULEDAYTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcludeFromStateReporting</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcludeFromStateReporting
	{
		get
		{ 
			return GetFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_EXCLUDEFROMSTATEREPORTING );
		}
		set
		{
			SetField( StudentDTD.SCHOOLINFOEXTENSIONS_EXCLUDEFROMSTATEREPORTING, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetExcludeFromStateReporting( YesNo val )
	{
		SetField( StudentDTD.SCHOOLINFOEXTENSIONS_EXCLUDEFROMSTATEREPORTING, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;DaysInSession&gt;</c> element.
	/// </summary>
	/// <value> The <c>DaysInSession</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string DaysInSession
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_DAYSINSESSION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_DAYSINSESSION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;LastInstructionDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>LastInstructionDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string LastInstructionDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_LASTINSTRUCTIONDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLINFOEXTENSIONS_LASTINSTRUCTIONDATE, new SifString( value ), value );
		}
	}

}}
