// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A SchoolCourseInfoExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class SchoolCourseInfoExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a SchoolCourseInfoExtensions
	/// </summary>
	public SchoolCourseInfoExtensions() : base ( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected SchoolCourseInfoExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;TermCode&gt;</c> element.
	/// </summary>
	/// <value> The <c>TermCode</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string TermCode
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_TERMCODE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_TERMCODE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SemesterLength&gt;</c> element.
	/// </summary>
	/// <value> The <c>SemesterLength</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? SemesterLength
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_SEMESTERLENGTH ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_SEMESTERLENGTH, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;CIPCodeNumber&gt;</c> element.
	/// </summary>
	/// <value> The <c>CIPCodeNumber</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string CIPCodeNumber
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_CIPCODENUMBER ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_CIPCODENUMBER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcludeFromStateReporting</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcludeFromStateReporting
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_EXCLUDEFROMSTATEREPORTING ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SCHOOLCOURSEINFOEXTENSIONS_EXCLUDEFROMSTATEREPORTING, new SifString( value ), value );
		}
	}

}}
