// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A SectionInfoExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class SectionInfoExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a SectionInfoExtensions
	/// </summary>
	public SectionInfoExtensions() : base ( StudentDTD.SECTIONINFOEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected SectionInfoExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;Teacher1ID&gt;</c> element.
	/// </summary>
	/// <value> The <c>Teacher1ID</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? Teacher1ID
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_TEACHER1ID ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_TEACHER1ID, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;WhereTaughtSchl&gt;</c> element.
	/// </summary>
	/// <value> The <c>WhereTaughtSchl</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? WhereTaughtSchl
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_WHERETAUGHTSCHL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_WHERETAUGHTSCHL, new SifInt( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;WhereTaughtDist&gt;</c> element.
	/// </summary>
	/// <value> The <c>WhereTaughtDist</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? WhereTaughtDist
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_WHERETAUGHTDIST ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.SECTIONINFOEXTENSIONS_WHERETAUGHTDIST, new SifInt( value ), value );
		}
	}

}}
