// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A StudentSectionEnrollmentExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class StudentSectionEnrollmentExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a StudentSectionEnrollmentExtensions
	/// </summary>
	public StudentSectionEnrollmentExtensions() : base ( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected StudentSectionEnrollmentExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;CourseMembership&gt;</c> element.
	/// </summary>
	/// <value> The <c>CourseMembership</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string CourseMembership
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_COURSEMEMBERSHIP ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_COURSEMEMBERSHIP, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;GradeEarned&gt;</c> element.
	/// </summary>
	/// <value> The <c>GradeEarned</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string GradeEarned
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_GRADEEARNED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_GRADEEARNED, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;CreditsEarned&gt;</c> element.
	/// </summary>
	/// <value> The <c>CreditsEarned</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public decimal? CreditsEarned
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_CREDITSEARNED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_CREDITSEARNED, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReportedExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReportedExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReportedExitDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_REPORTEDEXITDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_REPORTEDEXITDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ConcurrEnrolled&gt;</c> element.
	/// </summary>
	/// <value> The <c>ConcurrEnrolled</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ConcurrEnrolled
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_CONCURRENROLLED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSECTIONENROLLMENTEXTENSIONS_CONCURRENROLLED, new SifString( value ), value );
		}
	}

}}
