// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A StudentPersonalExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class StudentPersonalExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a StudentPersonalExtensions
	/// </summary>
	public StudentPersonalExtensions() : base ( StudentDTD.STUDENTPERSONALEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected StudentPersonalExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;DistrictOfResidence&gt;</c> element.
	/// </summary>
	/// <value> The <c>DistrictOfResidence</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string DistrictOfResidence
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_DISTRICTOFRESIDENCE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_DISTRICTOFRESIDENCE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AccompaniedStudent&gt;</c> element.
	/// </summary>
	/// <value> The <c>AccompaniedStudent</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string AccompaniedStudent
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ACCOMPANIEDSTUDENT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ACCOMPANIEDSTUDENT, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;MealStatus&gt;</c> element.
	/// </summary>
	/// <value> The <c>MealStatus</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string MealStatus
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MEALSTATUS ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MEALSTATUS, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;RaceObserved&gt;</c> element.
	/// </summary>
	/// <value> The <c>RaceObserved</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string RaceObserved
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_RACEOBSERVED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_RACEOBSERVED, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;CumulativeGPA&gt;</c> element.
	/// </summary>
	/// <value> The <c>CumulativeGPA</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string CumulativeGPA
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_CUMULATIVEGPA ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_CUMULATIVEGPA, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ResidentStatus&gt;</c> element.
	/// </summary>
	/// <value> The <c>ResidentStatus</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ResidentStatus
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_RESIDENTSTATUS ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_RESIDENTSTATUS, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ELLMonitoredDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ELLMonitoredDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ELLMonitoredDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELLMONITOREDDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELLMONITOREDDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;MilitaryChild&gt;</c> element.
	/// </summary>
	/// <value> The <c>MilitaryChild</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string MilitaryChild
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MILITARYCHILD ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MILITARYCHILD, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EconomicDisadv&gt;</c> element.
	/// </summary>
	/// <value> The <c>EconomicDisadv</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EconomicDisadv
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ECONOMICDISADV ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ECONOMICDISADV, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcludeFromStateReporting</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcludeFromStateReporting
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EXCLUDEFROMSTATEREPORTING ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EXCLUDEFROMSTATEREPORTING, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyGrad&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyGrad</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyGrad
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYGRAD ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYGRAD, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReadingIntervention&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReadingIntervention</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReadingIntervention
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READINGINTERVENTION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READINGINTERVENTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReadGradeLevel&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReadGradeLevel</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReadGradeLevel
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVEL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVEL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ELLInstructionType&gt;</c> element.
	/// </summary>
	/// <value> The <c>ELLInstructionType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ELLInstructionType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELLINSTRUCTIONTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELLINSTRUCTIONTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;HighSchoolExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>HighSchoolExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string HighSchoolExitDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHOOLEXITDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHOOLEXITDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReadGradeLevelFall&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReadGradeLevelFall</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReadGradeLevelFall
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVELFALL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVELFALL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReadGradeLevelSpring&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReadGradeLevelSpring</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReadGradeLevelSpring
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVELSPRING ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_READGRADELEVELSPRING, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;CTEProgramArea&gt;</c> element.
	/// </summary>
	/// <value> The <c>CTEProgramArea</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string CTEProgramArea
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_CTEPROGRAMAREA ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_CTEPROGRAMAREA, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;LimitedEnglish&gt;</c> element.
	/// </summary>
	/// <value> The <c>LimitedEnglish</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string LimitedEnglish
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_LIMITEDENGLISH ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_LIMITEDENGLISH, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyNumeracyStatusBOY&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyNumeracyStatusBOY</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyNumeracyStatusBOY
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSBOY ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSBOY, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ELProficiencyAssessment&gt;</c> element.
	/// </summary>
	/// <value> The <c>ELProficiencyAssessment</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ELProficiencyAssessment
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELPROFICIENCYASSESSMENT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ELPROFICIENCYASSESSMENT, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Biliteracy1Language&gt;</c> element.
	/// </summary>
	/// <value> The <c>Biliteracy1Language</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Biliteracy1Language
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY1LANGUAGE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY1LANGUAGE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PassedCivicsExam&gt;</c> element.
	/// </summary>
	/// <value> The <c>PassedCivicsExam</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string PassedCivicsExam
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_PASSEDCIVICSEXAM ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_PASSEDCIVICSEXAM, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyNumeracyStatusMOY&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyNumeracyStatusMOY</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyNumeracyStatusMOY
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSMOY ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSMOY, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyNumeracyStatusEOY&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyNumeracyStatusEOY</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyNumeracyStatusEOY
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSEOY ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYSTATUSEOY, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Biliteracy1Level&gt;</c> element.
	/// </summary>
	/// <value> The <c>Biliteracy1Level</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Biliteracy1Level
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY1LEVEL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY1LEVEL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyNumeracyIntervention&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyNumeracyIntervention</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyNumeracyIntervention
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYINTERVENTION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_EARLYNUMERACYINTERVENTION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Biliteracy2Language&gt;</c> element.
	/// </summary>
	/// <value> The <c>Biliteracy2Language</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Biliteracy2Language
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY2LANGUAGE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY2LANGUAGE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Biliteracy2Level&gt;</c> element.
	/// </summary>
	/// <value> The <c>Biliteracy2Level</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Biliteracy2Level
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY2LEVEL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BILITERACY2LEVEL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;HighSchlCompl&gt;</c> element.
	/// </summary>
	/// <value> The <c>HighSchlCompl</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string HighSchlCompl
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHLCOMPL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHLCOMPL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;RefugeeStudent&gt;</c> element.
	/// </summary>
	/// <value> The <c>RefugeeStudent</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string RefugeeStudent
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_REFUGEESTUDENT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_REFUGEESTUDENT, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;HighSchlComplStatus&gt;</c> element.
	/// </summary>
	/// <value> The <c>HighSchlComplStatus</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string HighSchlComplStatus
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHLCOMPLSTATUS ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_HIGHSCHLCOMPLSTATUS, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;SpecialEdExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>SpecialEdExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string SpecialEdExitDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_SPECIALEDEXITDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_SPECIALEDEXITDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;BeginYearROGLCompositeScore&gt;</c> element.
	/// </summary>
	/// <value> The <c>BeginYearROGLCompositeScore</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string BeginYearROGLCompositeScore
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BEGINYEARROGLCOMPOSITESCORE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_BEGINYEARROGLCOMPOSITESCORE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;MidYearROGLCompositeScore&gt;</c> element.
	/// </summary>
	/// <value> The <c>MidYearROGLCompositeScore</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string MidYearROGLCompositeScore
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MIDYEARROGLCOMPOSITESCORE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MIDYEARROGLCOMPOSITESCORE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EndYearROGLCompositeScore&gt;</c> element.
	/// </summary>
	/// <value> The <c>EndYearROGLCompositeScore</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EndYearROGLCompositeScore
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ENDYEARROGLCOMPOSITESCORE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_ENDYEARROGLCOMPOSITESCORE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;GeoCode&gt;</c> element.
	/// </summary>
	/// <value> The <c>GeoCode</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string GeoCode
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_GEOCODE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_GEOCODE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;MesaProgram&gt;</c> element.
	/// </summary>
	/// <value> The <c>MesaProgram</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string MesaProgram
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MESAPROGRAM ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_MESAPROGRAM, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NCLBSuppServMath&gt;</c> element.
	/// </summary>
	/// <value> The <c>NCLBSuppServMath</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string NCLBSuppServMath
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_NCLBSUPPSERVMATH ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_NCLBSUPPSERVMATH, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NCLBSuppServLang&gt;</c> element.
	/// </summary>
	/// <value> The <c>NCLBSuppServLang</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string NCLBSuppServLang
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_NCLBSUPPSERVLANG ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTPERSONALEXTENSIONS_NCLBSUPPSERVLANG, new SifString( value ), value );
		}
	}

}}
