// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A StudentSchoolEnrollmentExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class StudentSchoolEnrollmentExtensions : SifDataObject
{
	/// <summary>
	/// Creates an instance of a StudentSchoolEnrollmentExtensions
	/// </summary>
	public StudentSchoolEnrollmentExtensions() : base( Adk.SifVersion, StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected StudentSchoolEnrollmentExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;KindergartenType&gt;</c> element.
	/// </summary>
	/// <value> The <c>KindergartenType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string KindergartenType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_KINDERGARTENTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_KINDERGARTENTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EnrollmentValidationType&gt;</c> element.
	/// </summary>
	/// <value> The <c>EnrollmentValidationType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EnrollmentValidationType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ENROLLMENTVALIDATIONTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ENROLLMENTVALIDATIONTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;StudentStateProvidenceId&gt;</c> element.
	/// </summary>
	/// <value> The <c>StudentStateProvidenceId</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string StudentStateProvidenceId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_STUDENTSTATEPROVIDENCEID ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_STUDENTSTATEPROVIDENCEID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcludeFromStateReporting</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcludeFromStateReporting
	{
		get
		{ 
			return GetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING );
		}
		set
		{
			SetField( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetExcludeFromStateReporting( YesNo val )
	{
		SetField( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;DaysInMembership&gt;</c> element.
	/// </summary>
	/// <value> The <c>DaysInMembership</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public decimal? DaysInMembership
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSINMEMBERSHIP ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSINMEMBERSHIP, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReportedExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReportedExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReportedExitDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_REPORTEDEXITDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_REPORTEDEXITDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PartTimeHomeSchool&gt;</c> element.
	/// </summary>
	/// <value> The <c>PartTimeHomeSchool</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string PartTimeHomeSchool
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_PARTTIMEHOMESCHOOL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_PARTTIMEHOMESCHOOL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;DaysAttended&gt;</c> element.
	/// </summary>
	/// <value> The <c>DaysAttended</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string DaysAttended
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSATTENDED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSATTENDED, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcusedAbsences&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcusedAbsences</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcusedAbsences
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCUSEDABSENCES ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCUSEDABSENCES, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;UnexcusedAbsences&gt;</c> element.
	/// </summary>
	/// <value> The <c>UnexcusedAbsences</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string UnexcusedAbsences
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_UNEXCUSEDABSENCES ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_UNEXCUSEDABSENCES, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AbsencesDueToSuspension&gt;</c> element.
	/// </summary>
	/// <value> The <c>AbsencesDueToSuspension</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string AbsencesDueToSuspension
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ABSENCESDUETOSUSPENSION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ABSENCESDUETOSUSPENSION, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NonAttender&gt;</c> element.
	/// </summary>
	/// <value> The <c>NonAttender</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string NonAttender
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_NONATTENDER ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_NONATTENDER, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ResidentStatusX&gt;</c> element.
	/// </summary>
	/// <value> The <c>ResidentStatusX</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ResidentStatusX
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_RESIDENTSTATUSX ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_RESIDENTSTATUSX, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1Math&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1Math</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1Math
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1MATH ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1MATH, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1ELA&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1ELA</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1ELA
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1ELA ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1ELA, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1Science&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1Science</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1Science
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1SCIENCE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1SCIENCE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1Health&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1Health</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1Health
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1HEALTH ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1HEALTH, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1AcademicGuidance&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1AcademicGuidance</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1AcademicGuidance
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1ACADEMICGUIDANCE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1ACADEMICGUIDANCE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1SocialStudies&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1SocialStudies</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1SocialStudies
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1SOCIALSTUDIES ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1SOCIALSTUDIES, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1Vocational&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1Vocational</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1Vocational
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1VOCATIONAL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1VOCATIONAL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;IntergenerationalPovertyGrant&gt;</c> element.
	/// </summary>
	/// <value> The <c>IntergenerationalPovertyGrant</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string IntergenerationalPovertyGrant
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_INTERGENERATIONALPOVERTYGRANT ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_INTERGENERATIONALPOVERTYGRANT, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;AfterSchool21CCLC&gt;</c> element.
	/// </summary>
	/// <value> The <c>AfterSchool21CCLC</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string AfterSchool21CCLC
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_AFTERSCHOOL21CCLC ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_AFTERSCHOOL21CCLC, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ELStateSoftware&gt;</c> element.
	/// </summary>
	/// <value> The <c>ELStateSoftware</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ELStateSoftware
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ELSTATESOFTWARE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ELSTATESOFTWARE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EarlyChildhoodReadingStateSoftware&gt;</c> element.
	/// </summary>
	/// <value> The <c>EarlyChildhoodReadingStateSoftware</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EarlyChildhoodReadingStateSoftware
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EARLYCHILDHOODREADINGSTATESOFTWARE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EARLYCHILDHOODREADINGSTATESOFTWARE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;NCLBSchoolChoice&gt;</c> element.
	/// </summary>
	/// <value> The <c>NCLBSchoolChoice</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string NCLBSchoolChoice
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_NCLBSCHOOLCHOICE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_NCLBSCHOOLCHOICE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;Title1ParaPros&gt;</c> element.
	/// </summary>
	/// <value> The <c>Title1ParaPros</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string Title1ParaPros
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1PARAPROS ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_TITLE1PARAPROS, new SifString( value ), value );
		}
	}

}}
