// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A StudentAttendanceSummaryExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class StudentAttendanceSummaryExtensions : SifElement
{
	/// <summary>
	/// Creates an instance of a StudentAttendanceSummaryExtensions
	/// </summary>
	public StudentAttendanceSummaryExtensions() : base ( StudentDTD.STUDENTATTENDANCESUMMARYEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected StudentAttendanceSummaryExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;AbsencesDueToSuspension&gt;</c> element.
	/// </summary>
	/// <value> The <c>AbsencesDueToSuspension</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public int? AbsencesDueToSuspension
	{
		get
		{
			return (int?) GetSifSimpleFieldValue( StudentDTD.STUDENTATTENDANCESUMMARYEXTENSIONS_ABSENCESDUETOSUSPENSION ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTATTENDANCESUMMARYEXTENSIONS_ABSENCESDUETOSUSPENSION, new SifInt( value ), value );
		}
	}

}}
