// THIS FILE WAS AUTO-GENERATED BY ADKGEN -- DO NOT MODIFY!

//
// Copyright (c)1998-2011 Pearson Education, Inc. or its affiliate(s).
// All rights reserved.
//

using System;
using System.Text;
using System.Security.Permissions;
using System.Runtime.Serialization;
using OpenADK.Library;
using OpenADK.Library.Global;
using OpenADK.Library.us.Common;

namespace OpenADK.Library.us.Student{

/// <summary>A StudentSchoolEnrollmentExtensions</summary>
/// <remarks>
///
/// <para>Author: Generated by adkgen</para>
/// <para>Version: 2.4</para>
/// <para>Since: 2.4</para>
/// </remarks>
[Serializable]
public class StudentSchoolEnrollmentExtensions : SifDataObject
{
	/// <summary>
	/// Creates an instance of a StudentSchoolEnrollmentExtensions
	/// </summary>
	public StudentSchoolEnrollmentExtensions() : base( Adk.SifVersion, StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS ){}

	/// <summary>
	/// Constructor used by the .Net Serialization formatter
	/// </summary>
	[SecurityPermission( SecurityAction.Demand, SerializationFormatter=true )] 
	protected StudentSchoolEnrollmentExtensions( SerializationInfo info, StreamingContext context ) : base( info, context ) {} 
	/// <summary>
	/// Gets or sets the value of the <c>&lt;KindergartenType&gt;</c> element.
	/// </summary>
	/// <value> The <c>KindergartenType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string KindergartenType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_KINDERGARTENTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_KINDERGARTENTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;EnrollmentValidationType&gt;</c> element.
	/// </summary>
	/// <value> The <c>EnrollmentValidationType</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string EnrollmentValidationType
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ENROLLMENTVALIDATIONTYPE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_ENROLLMENTVALIDATIONTYPE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;StudentStateProvidenceId&gt;</c> element.
	/// </summary>
	/// <value> The <c>StudentStateProvidenceId</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string StudentStateProvidenceId
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_STUDENTSTATEPROVIDENCEID ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_STUDENTSTATEPROVIDENCEID, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <value> The <c>ExcludeFromStateReporting</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ExcludeFromStateReporting
	{
		get
		{ 
			return GetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING );
		}
		set
		{
			SetField( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING, value );
		}
	}

	/// <summary>
	/// Sets the value of the <c>&lt;ExcludeFromStateReporting&gt;</c> element.
	/// </summary>
	/// <param name="val">A YesNo object</param>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public void SetExcludeFromStateReporting( YesNo val )
	{
		SetField( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_EXCLUDEFROMSTATEREPORTING, val );
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;DaysInMembership&gt;</c> element.
	/// </summary>
	/// <value> The <c>DaysInMembership</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public decimal? DaysInMembership
	{
		get
		{
			return (decimal?) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSINMEMBERSHIP ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSINMEMBERSHIP, new SifDecimal( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;ReportedExitDate&gt;</c> element.
	/// </summary>
	/// <value> The <c>ReportedExitDate</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string ReportedExitDate
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_REPORTEDEXITDATE ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_REPORTEDEXITDATE, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;PartTimeHomeSchool&gt;</c> element.
	/// </summary>
	/// <value> The <c>PartTimeHomeSchool</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string PartTimeHomeSchool
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_PARTTIMEHOMESCHOOL ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_PARTTIMEHOMESCHOOL, new SifString( value ), value );
		}
	}

	/// <summary>
	/// Gets or sets the value of the <c>&lt;DaysAttended&gt;</c> element.
	/// </summary>
	/// <value> The <c>DaysAttended</c> element of this object.</value>
	/// <remarks>
	/// <para>Version: 2.4</para>
	/// <para>Since: 2.4</para>
	/// </remarks>
	public string DaysAttended
	{
		get
		{
			return (string) GetSifSimpleFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSATTENDED ) ;
		}
		set
		{
			SetFieldValue( StudentDTD.STUDENTSCHOOLENROLLMENTEXTENSIONS_DAYSATTENDED, new SifString( value ), value );
		}
	}

}}
