<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Library.Nunit.US</RootNamespace>
    <AssemblyName>Library.Nunit.US</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\</OutputPath>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>bin\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>

    <PackageReference Include="xunit.v3" Version="3.0.1" />

    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />

  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="res\*" />
    <EmbeddedResource Include="schemas\SIF*\**\*.xsd">
      <SubType></SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="data\**\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\core\OpenADK-NET-Core.csproj" />
    <ProjectReference Include="..\..\..\src\us\OpenADK-US-SDO.csproj" />
    <ProjectReference Include="..\..\core\src\OpenADK-Nunit-Core.csproj" />
  </ItemGroup>
</Project>