<Project>
  <PropertyGroup>
    <Product>USIMS Service Template</Product>

    <Company>Utah State Board of Education</Company>
    <Copyright>© Utah State Board of Education. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>

    <RootNamespace Condition="'$(RootNamespace)' == '' And !$(MSBuildProjectName.StartsWith('StudentClearinghouseService.'))">StudentClearinghouseService.$(MSBuildProjectName)</RootNamespace>
    <AssemblyName Condition="'$(AssemblyName)' == '' And !$(MSBuildProjectName.StartsWith('StudentClearinghouseService.'))">StudentClearinghouseService.$(MSBuildProjectName)</AssemblyName>

    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>

    <IsPackable Condition="'$(IsPackable)' == ''">false</IsPackable>
  </PropertyGroup>

  <!-- Compilation options -->
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>

    <LangVersion Condition="'$(MSBuildProjectExtension)' == '.csproj'">latest</LangVersion>
    <Nullable Condition="'$(MSBuildProjectExtension)' == '.csproj'">enable</Nullable>
    <Deterministic Condition="'$(MSBuildProjectExtension)' == '.csproj'">true</Deterministic>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Instructs the compiler to use SHA256 instead of SHA1 when adding file hashes to PDBs. -->
    <ChecksumAlgorithm>SHA256</ChecksumAlgorithm>

    <!-- Fixes a common error in targets implementing a NoBuild mode. -->
    <BuildProjectReferences Condition="'$(NoBuild)' == 'true'">false</BuildProjectReferences>
  </PropertyGroup>

  <!-- Folder layout -->
  <PropertyGroup>
    <RepoRelativeProjectDir>$([MSBuild]::MakeRelative($(RepositoryRoot), $(MSBuildProjectDirectory)))</RepoRelativeProjectDir>

    <IsBenchmarkProject Condition="$(MSBuildProjectName.EndsWith('.Performance'))">true</IsBenchmarkProject>
    <IsTestProject Condition="$(MSBuildProjectName.EndsWith('Tests')) OR $(MSBuildProjectName.EndsWith('.Test'))">true</IsTestProject>

    <IncludeSource>true</IncludeSource>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <!-- Default packages -->
  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReference Include="MinVer" Version="2.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
