<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SIFWorks.UnitTesting</RootNamespace>
    <AssemblyName>SIFWorks.UnitTesting</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Eval|AnyCPU' ">
    <OutputPath>bin\Eval\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'ReleaseDocs|AnyCPU' ">
    <OutputPath>bin\ReleaseDocs\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Internal|AnyCPU' ">
    <OutputPath>bin\Internal\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
    <Reference Include="nunit.core, Version=2.2.8.0, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\lib\nunit\nunit.core.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework, Version=2.4.3.0, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\lib\nunit\nunit.framework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Framework\.MySCMServerInfo" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\core\OpenADK-NET-Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Framework\InMemoryProgocolTest.cs" />
    <Compile Remove="AdkTest.cs" />
    <Compile Remove="AdkObjectParseHelper.cs" />
  </ItemGroup>
</Project>