<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OpenADK.Library.us</RootNamespace>
    <AssemblyName>OpenADK.SDO-US</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\SifWorks.Sdo-US.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'ReleaseDocs|AnyCPU' ">
    <OutputPath>bin\ReleaseDocs\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Internal|AnyCPU' ">
    <OutputPath>bin\Internal\</OutputPath>
    <DebugType>none</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Eval|AnyCPU' ">
    <OutputPath>bin\Eval\</OutputPath>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\lib\log4net.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\core\OpenADK-NET-Core.csproj" />
  </ItemGroup>
</Project>