<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Library.Nunit.US</RootNamespace>
    <AssemblyName>Library.Nunit.US</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\</OutputPath>
    <Configurations>Debug;Eval;Internal;PerfTest;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <NoWarn>618</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <NoWarn>0618</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'PerfTest|AnyCPU' ">
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Eval|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="res\*" />
    <EmbeddedResource Include="schemas\SIF*\**\*.xsd">
      <SubType></SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="data\**\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\core\OpenADK-NET-Core.csproj" />
    <ProjectReference Include="..\..\..\src\us\OpenADK-US-SDO.csproj" />
    <ProjectReference Include="..\..\core\src\OpenADK-Nunit-Core.csproj" />
  </ItemGroup>
</Project>