<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\lib\log4net.dll</HintPath>
    </Reference>
    <Reference Include="Org.Mentalis.Security, Version=1.0.14.25108, Culture=neutral">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\lib\Org.Mentalis.Security.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\au\OpenADK-AU-SDO.csproj" />
    <ProjectReference Include="..\..\..\..\src\core\OpenADK-NET-Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Backup\SIFQuery.cs" />
    <Compile Remove="Backup\Properties\AssemblyInfo.cs" />
    <Compile Remove="Backup\ADKExamples.cs" />
  </ItemGroup>
</Project>