<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Exe</OutputType>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Commandlineparameters>/zone TestZoneA /url http://127.0.0.1:7080/MyEnterprise/TestZoneA /pull /freq 10</Commandlineparameters>
    <Externalconsole>true</Externalconsole>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\core\OpenADK-NET-Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\us\OpenADK-US-SDO.csproj" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Backup\SIFQuery.cs" />
    <Compile Remove="Backup\Properties\AssemblyInfo.cs" />
    <Compile Remove="Backup\ADKExamples.cs" />
  </ItemGroup>
</Project>