<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Edustructures.SIFWorks.Nunit.UK</RootNamespace>
    <AssemblyName>Edustructures.SIFWorks.nunit.uk</AssemblyName>
	<LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;PerfTest;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="data\SIF*\*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="schemas\SIF*\*.xsd">
      <SubType></SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\core\OpenADK-NET-Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\uk\OpenADK-UK-SDO.csproj" />
    <ProjectReference Include="..\..\..\core\src\OpenADK-Nunit-Core.csproj" />
  </ItemGroup>
</Project>