<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <Optimize>false</Optimize>
    <WarningLevel>1</WarningLevel>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Eval|AnyCPU' ">
    <OutputPath>bin\Eval\</OutputPath>
    <WarningLevel>1</WarningLevel>
    <DebugType></DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
    <Reference Update="System">
      <Name>System</Name>
    </Reference>
    <Reference Update="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Include="System.Design">
      <Name>System.Design</Name>
    </Reference>
    <Reference Update="System.Drawing">
      <Name>System.Drawing</Name>
    </Reference>
    <Reference Include="System.Management">
      <Name>System.Management</Name>
    </Reference>
    <Reference Update="System.Xml">
      <Name>System.XML</Name>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="agent.cfg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Students.mdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\au\OpenADK-AU-SDO.csproj" />
    <ProjectReference Include="..\..\..\..\src\core\OpenADK-NET-Core.csproj" />
  </ItemGroup>
  <PropertyGroup />
</Project>
