<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Library.Examples.SimpleSubscriber</RootNamespace>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Eval;Internal;Release;ReleaseDocs</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'ReleaseDocs|AnyCPU' ">
    <OutputPath>bin\ReleaseDocs\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Internal|AnyCPU' ">
    <OutputPath>bin\Internal\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Eval|AnyCPU' ">
    <OutputPath>bin\Eval\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\core\OpenADK-NET-Core.csproj" />
    <ProjectReference Include="..\..\..\..\src\us\OpenADK-US-SDO.csproj" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Backup\StudentPersonalHandler.cs" />
    <Compile Remove="Backup\SimpleSubscriber.cs" />
    <Compile Remove="Backup\Properties\AssemblyInfo.cs" />
    <Compile Remove="Backup\ADKExamples.cs" />
  </ItemGroup>
</Project>